const KNOWN_VPNS = {
    "1.66": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "1.55": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "14.11": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "14.52": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "14.56": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "15.53": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "31.10": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "39.111": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "42.147": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "49.1": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "49.228": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "49.164": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "58.3": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "58.87": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "58.152": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "58.227": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "59.20": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "59.23": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "69.129": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "59.138": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "60.69": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "60.122": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "60.137": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "60.141": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "61.21": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "61.75": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "79.105": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "82.1": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "85.175": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "88.222": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "90.150": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "91.196": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "91.218": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "92.124": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "94.255": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "95.25": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "101.128": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "100.35": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "103.152": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "109.252": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "111.106": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "113.22": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "114.204": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "114.206": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "117.3": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "118.68": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "119.24": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "121.109": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "121.138": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "121.161": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "122.222": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "123.198": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "124.18": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "124.110": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "125.14": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "126.77": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "126.78": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "126.142": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "126.147": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "126.208": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "138.64": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "138.229": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "150.9": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "153.168": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "158.169": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "160.13": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "173.195": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "176.212": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "178.34": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "180.5": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "180.30": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "180.97": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "180.200": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "184.22": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "185.201": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "195.208": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "203.179": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "212.32": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "219.100": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "219.104": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "222.113": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "222.148": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "223.204": { name: "VPN-gate", domain: "www.tsukuba.ac.jp" },
    "2.58": { name: "Proton VPN", domain: "protonvpn.com" },
    "5.8": { name: "Proton VPN", domain: "protonvpn.com" },
    "5.157": { name: "Proton VPN", domain: "protonvpn.com" },
    "5.181": { name: "Proton VPN", domain: "protonvpn.com" },
    "31.13": { name: "Proton VPN", domain: "protonvpn.com" },
    "37.19": { name: "Proton VPN", domain: "protonvpn.com" },
    "37.46": { name: "Proton VPN", domain: "protonvpn.com" },
    "37.120": { name: "Proton VPN", domain: "protonvpn.com" },
    "37.221": { name: "Proton VPN", domain: "protonvpn.com" },
    "45.14": { name: "Proton VPN", domain: "protonvpn.com" },
    "45.38": { name: "Proton VPN", domain: "protonvpn.com" },
    "45.87": { name: "Proton VPN", domain: "protonvpn.com" },
    "45.128": { name: "Proton VPN", domain: "protonvpn.com" },
    "45.134": { name: "Proton VPN", domain: "protonvpn.com" },
    "45.152": { name: "Proton VPN", domain: "protonvpn.com" },
    "62.112": { name: "Proton VPN", domain: "protonvpn.com" },
    "66.90": { name: "Proton VPN", domain: "protonvpn.com" },
    "66.115": { name: "Proton VPN", domain: "protonvpn.com" },
    "66.251": { name: "Proton VPN", domain: "protonvpn.com" },
    "69.10": { name: "Proton VPN", domain: "protonvpn.com" },
    "74.63": { name: "Proton VPN", domain: "protonvpn.com" },
    "77.247": { name: "Proton VPN", domain: "protonvpn.com" },
    "79.110": { name: "Proton VPN", domain: "protonvpn.com" },
    "79.135": { name: "Proton VPN", domain: "protonvpn.com" },
    "80.79": { name: "Proton VPN", domain: "protonvpn.com" },
    "84.17": { name: "Proton VPN", domain: "protonvpn.com" },
    "84.247": { name: "Proton VPN", domain: "protonvpn.com" },
    "84.252": { name: "Proton VPN", domain: "protonvpn.com" },
    "85.132": { name: "Proton VPN", domain: "protonvpn.com" },
    "85.159": { name: "Proton VPN", domain: "protonvpn.com" },
    "85.204": { name: "Proton VPN", domain: "protonvpn.com" },
    "85.206": { name: "Proton VPN", domain: "protonvpn.com" },
    "87.249": { name: "Proton VPN", domain: "protonvpn.com" },
    "89.36": { name: "Proton VPN", domain: "protonvpn.com" },
    "89.38": { name: "Proton VPN", domain: "protonvpn.com" },
    "89.39": { name: "Proton VPN", domain: "protonvpn.com" },
    "89.45": { name: "Proton VPN", domain: "protonvpn.com" },
    "89.187": { name: "Proton VPN", domain: "protonvpn.com" },
    "91.90": { name: "Proton VPN", domain: "protonvpn.com" },
    "91.219": { name: "Proton VPN", domain: "protonvpn.com" },
    "92.223": { name: "Proton VPN", domain: "protonvpn.com" },
    "93.113": { name: "Proton VPN", domain: "protonvpn.com" },
    "94.137": { name: "Proton VPN", domain: "protonvpn.com" },
    "102.38": { name: "Proton VPN", domain: "protonvpn.com" },
    "102.218": { name: "Proton VPN", domain: "protonvpn.com" },
    "103.75": { name: "Proton VPN", domain: "protonvpn.com" },
    "103.107": { name: "Proton VPN", domain: "protonvpn.com" },
    "103.108": { name: "Proton VPN", domain: "protonvpn.com" },
    "103.125": { name: "Proton VPN", domain: "protonvpn.com" },
    "103.214": { name: "Proton VPN", domain: "protonvpn.com" },
    "103.216": { name: "Proton VPN", domain: "protonvpn.com" },
    "103.230": { name: "Proton VPN", domain: "protonvpn.com" },
    "104.234": { name: "Proton VPN", domain: "protonvpn.com" },
    "107.181": { name: "Proton VPN", domain: "protonvpn.com" },
    "107.186": { name: "Proton VPN", domain: "protonvpn.com" },
    "116.90": { name: "Proton VPN", domain: "protonvpn.com" },
    "138.199": { name: "Proton VPN", domain: "protonvpn.com" },
    "144.48": { name: "Proton VPN", domain: "protonvpn.com" },
    "146.70": { name: "Proton VPN", domain: "protonvpn.com" },
    "149.34": { name: "Proton VPN", domain: "protonvpn.com" },
    "149.36": { name: "Proton VPN", domain: "protonvpn.com" },
    "149.88": { name: "Proton VPN", domain: "protonvpn.com" },
    "149.102": { name: "Proton VPN", domain: "protonvpn.com" },
    "152.53": { name: "Proton VPN", domain: "protonvpn.com" },
    "154.47": { name: "Proton VPN", domain: "protonvpn.com" },
    "156.146": { name: "Proton VPN", domain: "protonvpn.com" },
    "165.231": { name: "Proton VPN", domain: "protonvpn.com" },
    "169.150": { name: "Proton VPN", domain: "protonvpn.com" },
    "172.83": { name: "Proton VPN", domain: "protonvpn.com" },
    "172.98": { name: "Proton VPN", domain: "protonvpn.com" },
    "178.218": { name: "Proton VPN", domain: "protonvpn.com" },
    "178.249": { name: "Proton VPN", domain: "protonvpn.com" },
    "180.149": { name: "Proton VPN", domain: "protonvpn.com" },
    "185.51": { name: "Proton VPN", domain: "protonvpn.com" },
    "185.76": { name: "Proton VPN", domain: "protonvpn.com" },
    "185.107": { name: "Proton VPN", domain: "protonvpn.com" },
    "185.156": { name: "Proton VPN", domain: "protonvpn.com" },
    "185.159": { name: "Proton VPN", domain: "protonvpn.com" },
    "185.185": { name: "Proton VPN", domain: "protonvpn.com" },
    "185.229": { name: "Proton VPN", domain: "protonvpn.com" },
    "185.230": { name: "Proton VPN", domain: "protonvpn.com" },
    "185.246": { name: "Proton VPN", domain: "protonvpn.com" },
    "188.214": { name: "Proton VPN", domain: "protonvpn.com" },
    "188.215": { name: "Proton VPN", domain: "protonvpn.com" },
    "188.241": { name: "Proton VPN", domain: "protonvpn.com" },
    "190.2": { name: "Proton VPN", domain: "protonvpn.com" },
    "193.27": { name: "Proton VPN", domain: "protonvpn.com" },
    "193.29": { name: "Proton VPN", domain: "protonvpn.com" },
    "193.37": { name: "Proton VPN", domain: "protonvpn.com" },
    "193.148": { name: "Proton VPN", domain: "protonvpn.com" },
    "194.34": { name: "Proton VPN", domain: "protonvpn.com" },
    "194.126": { name: "Proton VPN", domain: "protonvpn.com" },
    "195.80": { name: "Proton VPN", domain: "protonvpn.com" },
    "195.158": { name: "Proton VPN", domain: "protonvpn.com" },
    "195.181": { name: "Proton VPN", domain: "protonvpn.com" },
    "196.240": { name: "Proton VPN", domain: "protonvpn.com" },
    "196.244": { name: "Proton VPN", domain: "protonvpn.com" },
    "196.245": { name: "Proton VPN", domain: "protonvpn.com" },
    "212.30": { name: "Proton VPN", domain: "protonvpn.com" },
    "212.102": { name: "Proton VPN", domain: "protonvpn.com" },
    "212.104": { name: "Proton VPN", domain: "protonvpn.com" },
    "217.138": { name: "Proton VPN", domain: "protonvpn.com" },
    "45.129": { name: "Surfshark", domain: "surfshark.com" },
    "139.28": { name: "Surfshark", domain: "surfshark.com" },
    "156.146": { name: "Mullvad VPN", domain: "mullvad.net" },
    "185.213": { name: "Mullvad VPN", domain: "mullvad.net" },
    "198.18": { name: "ExpressVPN", domain: "expressvpn.com" },
    "149.154": { name: "ExpressVPN", domain: "expressvpn.com" },
    "172.83": { name: "Private Internet Access", domain: "privateinternetaccess.com" },
    "154.16": { name: "Private Internet Access", domain: "privateinternetaccess.com" },
    "64.120": { name: "TorGuard", domain: "torguard.net" },
    "176.113": { name: "TorGuard", domain: "torguard.net" },
    "23.94": { name: "Windscribe", domain: "windscribe.com" },
    "198.23": { name: "Windscribe", domain: "windscribe.com" }
};
